package ru.rockxi.fff.ui.remote

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.ArrowBack
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import ru.rockxi.fff.data.harness.KeystoreHarnessTokenStore
import ru.rockxi.fff.data.remote.*
import ru.rockxi.fff.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun RemoteScreen(onBack:()->Unit){val context=LocalContext.current;val vm:RemoteViewModel=viewModel(factory=RemoteViewModel.factory(HttpRemoteApi(),KeystoreHarnessTokenStore(context)));val s by vm.state.collectAsStateWithLifecycle();var add by remember{mutableStateOf(false)};var agent by remember{mutableStateOf(false)}
 Scaffold(containerColor=FffBackground,topBar={TopAppBar(title={Text("Remote Control",fontWeight=FontWeight.Bold)},navigationIcon={IconButton(onBack){Icon(Icons.AutoMirrored.Rounded.ArrowBack,"Назад")}},actions={IconButton(vm::reload){Icon(Icons.Rounded.Refresh,"Обновить")}},colors=TopAppBarDefaults.topAppBarColors(containerColor=FffBackground))}){p->
  if(!s.paired)Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){Text(s.error?:"Сначала подключите AI Harness",color=FffMuted)} else LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
   item{Header("SSH-ХОСТЫ",{add=true},"Добавить")}
   items(s.hosts,key={it.id}){h->Card(colors=CardDefaults.cardColors(containerColor=if(s.selectedHostId==h.id)FffMint.copy(.12f) else FffSurface),modifier=Modifier.fillMaxWidth().clickable{vm.selectHost(h.id)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(h.name,fontWeight=FontWeight.Bold);Text("${h.username}@${h.hostname}:${h.port} · ${if(h.authType=="key")"ключ" else "пароль"}",color=FffMuted);h.jumpHostId?.let{Text("ProxyJump: ${s.hosts.firstOrNull{x->x.id==it}?.name?:it}",color=FffMuted)}};IconButton({vm.deleteHost(h.id)}){Icon(Icons.Rounded.Delete,"Удалить")}}}}
   item{Terminal(s,vm::runCommand)}
   item{Header("CODEX CLI",{agent=true},"Запустить")}
   items(s.sessions,key={it.id}){x->Card(colors=CardDefaults.cardColors(containerColor=FffSurface),modifier=Modifier.fillMaxWidth().clickable{vm.openSession(x.id)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.title?:x.prompt.take(48),fontWeight=FontWeight.Bold);Text(x.status+(x.exitCode?.let{" · exit $it"}?:""),color=FffMuted)};if(x.status in listOf("starting","running"))IconButton({vm.stopSession(x.id)}){Icon(Icons.Rounded.Stop,"Остановить")}}}}
   if(s.error!=null)item{Text(s.error!!,color=Color(0xFFFF7C9B))};if(s.busy)item{LinearProgressIndicator(Modifier.fillMaxWidth())}
  }
 }
 if(add)HostDialog(s.hosts,{add=false}){add=false;vm.createHost(it)};if(agent)AgentDialog(s.selectedHostId!=null,s.busy,{agent=false}){p,t,d->agent=false;vm.startSession(p,t,d)};s.selectedSessionId?.let{id->SessionDialog(s,s.sessions.firstOrNull{it.id==id},{vm.stopSession(id)},vm::closeSession)}
}
@Composable private fun Header(title:String,action:()->Unit,label:String)=Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(title,Modifier.weight(1f),color=FffMint,fontFamily=FontFamily.Monospace);Button(action){Text(label)}}
@Composable private fun Terminal(s:RemoteState,run:(String,Int)->Unit){var command by remember{mutableStateOf("")};var timeout by remember{mutableStateOf("30")};Card(colors=CardDefaults.cardColors(containerColor=FffSurface)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("КОМАНДНАЯ СТРОКА",color=FffMint,fontFamily=FontFamily.Monospace);OutlinedTextField(command,{command=it.take(8000)},Modifier.fillMaxWidth(),label={Text("Команда")},minLines=2);OutlinedTextField(timeout,{timeout=it.filter(Char::isDigit).take(3)},label={Text("Таймаут, сек")});Button({run(command,(timeout.toIntOrNull()?:30).coerceIn(1,120))},enabled=s.selectedHostId!=null&&command.isNotBlank()&&!s.busy){Text("Выполнить")};if(s.commandOutput.isNotEmpty()||s.commandExitCode!=null){Text("exit: ${s.commandExitCode?:"—"}${if(s.commandTruncated)" · вывод обрезан" else ""}",color=FffMuted);Text(s.commandOutput,Modifier.fillMaxWidth().background(Color.Black,RoundedCornerShape(8.dp)).padding(10.dp),fontFamily=FontFamily.Monospace,color=Color(0xFFD8FFE9))}}}}
@Composable private fun HostDialog(hosts:List<RemoteHost>,dismiss:()->Unit,save:(NewHost)->Unit){var name by remember{mutableStateOf("")};var hostname by remember{mutableStateOf("")};var port by remember{mutableStateOf("22")};var username by remember{mutableStateOf("")};var auth by remember{mutableStateOf("password")};var secret by remember{mutableStateOf("")};var passphrase by remember{mutableStateOf("")};var jump by remember{mutableStateOf<String?>(null)};Dialog(onDismissRequest=dismiss){Card{LazyColumn(Modifier.padding(18.dp).fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Новое SSH-подключение",fontWeight=FontWeight.Bold)};item{OutlinedTextField(name,{name=it},label={Text("Название")})};item{OutlinedTextField(hostname,{hostname=it},label={Text("Адрес/IP")})};item{Row{OutlinedTextField(port,{port=it.filter(Char::isDigit)},Modifier.width(100.dp),label={Text("Порт")});Spacer(Modifier.width(8.dp));OutlinedTextField(username,{username=it},Modifier.weight(1f),label={Text("Логин")})}};item{Row{FilterChip(auth=="password",{auth="password"},{Text("Пароль")});Spacer(Modifier.width(8.dp));FilterChip(auth=="key",{auth="key"},{Text("Ключ")})}};item{OutlinedTextField(secret,{secret=it},Modifier.fillMaxWidth(),label={Text(if(auth=="key")"Приватный ключ" else "Пароль")},visualTransformation=if(auth=="password")PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,minLines=if(auth=="key")4 else 1)};if(auth=="key")item{OutlinedTextField(passphrase,{passphrase=it},label={Text("Passphrase (необязательно)")},visualTransformation=PasswordVisualTransformation())};if(hosts.isNotEmpty())item{Text("ProxyJump",color=FffMuted);Row(Modifier.horizontalScroll(rememberScrollState())){FilterChip(jump==null,{jump=null},{Text("Нет")});hosts.forEach{h->Spacer(Modifier.width(6.dp));FilterChip(jump==h.id,{jump=h.id},{Text(h.name)})}}};item{Text("Секрет отправляется один раз и не сохраняется на телефоне.",color=FffMuted);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){TextButton(dismiss){Text("Отмена")};Button({save(NewHost(name.trim(),hostname.trim(),port.toIntOrNull()?:22,username.trim(),auth,secret,passphrase.takeIf{it.isNotBlank()},jump))},enabled=name.isNotBlank()&&hostname.isNotBlank()&&username.isNotBlank()&&secret.isNotBlank()){Text("Сохранить")}}}}}}}
internal fun canStartRemoteAgent(hasHost:Boolean,busy:Boolean,prompt:String)=hasHost&&!busy&&prompt.isNotBlank()
@Composable private fun AgentDialog(hasAvailableHost:Boolean,busy:Boolean,dismiss:()->Unit,start:(String,String?,String?)->Unit){var prompt by remember{mutableStateOf("")};var title by remember{mutableStateOf("")};var dir by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Запустить Codex CLI")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){if(!hasAvailableHost)Text("Сначала выберите или добавьте SSH-хост. Введённая задача останется в форме.",color=Color(0xFFFFB86B));OutlinedTextField(prompt,{prompt=it},label={Text("Задача")},minLines=4);OutlinedTextField(title,{title=it},label={Text("Название (необязательно)")});OutlinedTextField(dir,{dir=it},label={Text("Рабочая папка")})}},confirmButton={Button({start(prompt,title,dir)},enabled=canStartRemoteAgent(hasAvailableHost,busy,prompt)){Text("Запустить в фоне")}},dismissButton={TextButton(dismiss){Text("Отмена")}})}
@Composable private fun SessionDialog(s:RemoteState,session:RemoteSession?,stop:()->Unit,dismiss:()->Unit)=AlertDialog(onDismissRequest=dismiss,title={Text(session?.title?:"Codex-сессия")},text={Column{Text(session?.status?:"",color=FffMuted);s.sessionOutputTruncatedBefore?.let{Text("Начало вывода удалено до позиции $it",color=Color(0xFFFFB86B))};Box(Modifier.fillMaxWidth().heightIn(min=220.dp,max=500.dp).background(Color.Black).verticalScroll(rememberScrollState()).padding(10.dp)){Text(s.sessionOutput.ifEmpty{"Ожидание вывода…"},fontFamily=FontFamily.Monospace,color=Color(0xFFD8FFE9))}}},confirmButton={if(session?.status in listOf("starting","running"))Button(stop){Text("Остановить")}},dismissButton={TextButton(dismiss){Text("Закрыть")}})
