package ru.rockxi.fff.ui.harness
import androidx.lifecycle.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
import ru.rockxi.fff.data.harness.*
import java.util.UUID

internal sealed interface HarnessPhase{data object Unpaired:HarnessPhase;data class Pairing(val code:String):HarnessPhase;data object Paired:HarnessPhase;data object Revoking:HarnessPhase}
internal data class HarnessState(val phase:HarnessPhase=HarnessPhase.Unpaired,val conversations:List<HarnessConversation> = emptyList(),val selected:HarnessConversation?=null,val messages:List<ServerMessage> = emptyList(),val draft:String="",val nextBefore:Long?=null,val loading:Boolean=false,val loadingOlder:Boolean=false,val sending:Boolean=false,val error:String?=null,val retryText:String?=null,val composerError:String?=null,val showArchived:Boolean=false,val prependedCount:Int=0,val codexAuth:CodexAuth=CodexAuth(CodexAuthState.UNKNOWN),val codexModels:List<String> = emptyList(),val provider:HarnessProvider=HarnessProvider.AGENT,val selectedModel:String?=null,val codexBusy:Boolean=false)
internal class HarnessViewModel(private val api:HarnessApi,private val tokens:HarnessTokenStore,private val io:CoroutineDispatcher=Dispatchers.IO):ViewModel(){
 private var screenActive=false;private var token=tokens.load();private var pending=tokens.pendingRevoke();private var pendingAssistantAfter:Pair<String,Long>?=null;private val mutable=MutableStateFlow(HarnessState(phase=if(pending!=null)HarnessPhase.Revoking else if(token!=null)HarnessPhase.Paired else HarnessPhase.Unpaired));val state=mutable.asStateFlow();private var pairingJob:Job?=null;private var eePoll:Job?=null;private var codexPoll:Job?=null;private var codexStatusJob:Job?=null;private var codexCommandJob:Job?=null;private var codexGeneration=0L
 init{if(pending!=null)retryPendingRevoke() else if(token!=null)refreshConversations()}
 fun setScreenActive(active:Boolean){screenActive=active;if(!active){eePoll?.cancel();codexPoll?.cancel()}else{if(mutable.value.selected?.kind==ConversationKind.EE)startEePoll();if(token!=null){if(mutable.value.codexAuth.state==CodexAuthState.PENDING)startCodexPoll() else refreshCodexAuth()}}}
 fun pair(){if(mutable.value.loading||pairingJob?.isActive==true)return;mutable.value=mutable.value.copy(loading=true,error=null);pairingJob=viewModelScope.launch{try{val s=withContext(io){api.start(tokens.deviceId())};mutable.value=mutable.value.copy(phase=HarnessPhase.Pairing(s.code),loading=false);var pause=1000L;while(true){delay(pause);when(val r=withContext(io){api.poll(s.pairingId,s.pollSecret)}){PollResult.Pending->pause=(pause*2).coerceAtMost(8000);PollResult.Delivered->error("Ключ уже получен. Начните заново.");is PollResult.Token->{token=r.value;tokens.save(r.value);mutable.value=mutable.value.copy(phase=HarnessPhase.Paired,loading=false);refreshConversations();if(screenActive)refreshCodexAuth();break}}}}catch(c:CancellationException){throw c}catch(e:Throwable){mutable.value=mutable.value.copy(phase=HarnessPhase.Unpaired,loading=false,error=e.message)}}}
 fun refreshConversations(){val bearer=token?:return;mutable.value=mutable.value.copy(loading=true,error=null);viewModelScope.launch{call{api.listConversations(bearer,mutable.value.showArchived)}?.let{all->val list=if(mutable.value.showArchived)all.filter{it.archived}else all.filter{!it.archived};mutable.value=mutable.value.copy(conversations=list.sortedWith(compareByDescending<HarnessConversation>{it.kind==ConversationKind.EE}.thenByDescending{it.updatedAt}),loading=false)}}}
 fun toggleArchived(){mutable.value=mutable.value.copy(showArchived=!mutable.value.showArchived);refreshConversations()}
 fun create(title:String){mutate{api.createConversation(it,title.trim()).also(::open)}}
 fun rename(title:String){val c=mutable.value.selected?:return;if(c.kind!=ConversationKind.EE)mutate{api.updateConversation(it,c.id,title=title.trim()).also(::replace)}}
 fun archive(value:Boolean){val c=mutable.value.selected?:return;if(c.kind!=ConversationKind.EE)mutate{api.updateConversation(it,c.id,archived=value);close();refreshConversations()}}
 fun delete(){val c=mutable.value.selected?:return;if(c.kind!=ConversationKind.EE)mutate{api.deleteConversation(it,c.id);close();refreshConversations()}}
 fun open(c:HarnessConversation){eePoll?.cancel();pendingAssistantAfter=null;val provider=if(c.kind==ConversationKind.EE)HarnessProvider.AGENT else tokens.provider(c.id);mutable.value=mutable.value.copy(selected=c,messages=emptyList(),draft=tokens.draft(c.id),nextBefore=null,loading=true,error=null,retryText=null,composerError=null,prependedCount=0,provider=provider,selectedModel=if(c.kind==ConversationKind.EE)null else tokens.model(c.id));loadMessages();if(c.kind==ConversationKind.EE&&screenActive)startEePoll();normalizeCodexSelection()}
 fun close(){eePoll?.cancel();pendingAssistantAfter=null;mutable.value=mutable.value.copy(selected=null,messages=emptyList(),draft="",error=null)}
 fun updateDraft(value:String){val c=mutable.value.selected?:return;val clean=truncateUtf8(value,MAX_MESSAGE_BYTES);tokens.saveDraft(c.id,clean);mutable.value=mutable.value.copy(draft=clean,composerError=if(clean!=value)"Лимит — 20 000 байт UTF-8" else null)}
 fun selectProvider(provider:HarnessProvider){val c=mutable.value.selected?:return;if(c.kind==ConversationKind.EE)return;if(provider==HarnessProvider.CODEX&&(mutable.value.codexAuth.state!=CodexAuthState.CONNECTED||mutable.value.codexModels.isEmpty()))return;tokens.saveProvider(c.id,provider);mutable.value=mutable.value.copy(provider=provider);normalizeCodexSelection()}
 fun selectModel(model:String){val c=mutable.value.selected?:return;if(c.kind==ConversationKind.EE||model !in mutable.value.codexModels)return;tokens.saveModel(c.id,model);mutable.value=mutable.value.copy(selectedModel=model,provider=HarnessProvider.CODEX);tokens.saveProvider(c.id,HarnessProvider.CODEX)}
 fun loadOlder(){if(mutable.value.nextBefore==null||mutable.value.loadingOlder)return;loadMessages(true)}
 private fun loadMessages(older:Boolean=false){val bearer=token?:return;val c=mutable.value.selected?:return;if(older)mutable.value=mutable.value.copy(loadingOlder=true);viewModelScope.launch{val page=call{api.messages(bearer,c.id,if(older)mutable.value.nextBefore else null)};applyPage(c.id,page,older)}}
 private fun applyPage(id:String,page:MessagePage?,older:Boolean,mergeLatest:Boolean=false){if(page==null||mutable.value.selected?.id!=id)return;val prior=mutable.value.messages;val merged=if(older||mergeLatest)(page.items+prior)else page.items;val awaited=pendingAssistantAfter;val answered=awaited?.first==id&&page.items.any{it.role=="assistant"&&it.sequence>awaited.second};if(answered)pendingAssistantAfter=null;mutable.value=mutable.value.copy(messages=merged.distinctBy{it.id}.sortedBy{it.sequence},nextBefore=if(mergeLatest)mutable.value.nextBefore else page.nextBefore,loading=false,loadingOlder=false,sending=if(answered)false else mutable.value.sending,prependedCount=if(older)(merged.map{it.id}.toSet()-prior.map{it.id}.toSet()).size else 0)}
 fun send(){val c=mutable.value.selected?:return;val text=mutable.value.draft.trim();if(text.isEmpty()||mutable.value.sending)return;if(text.toByteArray().size>MAX_MESSAGE_BYTES){mutable.value=mutable.value.copy(composerError="Лимит — 20 000 байт UTF-8");return};sendText(c,text)}
 fun retry(){val c=mutable.value.selected?:return;val text=mutable.value.retryText?:return;val pending=tokens.pendingMessage(c.id);if(pending?.text==text)dispatchSend(c,pending)else sendText(c,text)}
 private fun sendText(c:HarnessConversation,text:String){val provider=if(c.kind==ConversationKind.EE)HarnessProvider.AGENT else mutable.value.provider;val model=if(provider==HarnessProvider.CODEX)mutable.value.selectedModel else null;if(provider==HarnessProvider.CODEX&&model==null){mutable.value=mutable.value.copy(composerError="Выберите модель Codex");return};val prior=tokens.pendingMessage(c.id);val request=if(prior?.text==text&&prior.provider==provider&&prior.model==model)prior else PendingHarnessMessage(UUID.randomUUID().toString(),text,provider,model).also{tokens.savePendingMessage(c.id,it)};dispatchSend(c,request)}
 private fun dispatchSend(c:HarnessConversation,request:PendingHarnessMessage){val bearer=token?:return;mutable.value=mutable.value.copy(sending=true,error=null,retryText=null);viewModelScope.launch{val result=call{api.send(bearer,c.id,request.text,request.clientId,request.provider,request.model)};if(result!=null){tokens.savePendingMessage(c.id,null);tokens.saveDraft(c.id,"");pendingAssistantAfter=if(result.pending)c.id to result.message.sequence else null;mutable.value=mutable.value.copy(draft="",sending=result.pending,retryText=null,composerError=null);loadMessages();refreshConversations();if(result.pending&&screenActive)startEePoll()}else mutable.value=mutable.value.copy(sending=false,retryText=request.text)}}
 private fun startEePoll(){eePoll?.cancel();val c=mutable.value.selected?:return;val bearer=token?:return;eePoll=viewModelScope.launch{while(isActive&&screenActive&&mutable.value.selected?.id==c.id){delay(3000);val page=call{api.messages(bearer,c.id,null)};applyPage(c.id,page,false,true)}}}
 fun refreshCodexAuth(){val bearer=token?:return;if(mutable.value.codexBusy)return;val generation=nextCodexGeneration(cancelPoll=false);codexStatusJob=viewModelScope.launch{val auth=call{api.codexAuthStatus(bearer)}?:return@launch;if(generation==codexGeneration&&!mutable.value.codexBusy)applyCodexAuth(auth,generation)}}
 fun startCodexAuth(){runCodexCommand{api.startCodexAuth(it)}}
 fun restartCodexAuth(){val bearer=token?:return;if(mutable.value.codexBusy||codexCommandJob?.isActive==true)return;val generation=nextCodexGeneration(cancelPoll=true);mutable.value=mutable.value.copy(codexBusy=true,error=null);codexCommandJob=viewModelScope.launch{val loggedOut=call{api.logoutCodex(bearer)};if(generation!=codexGeneration)return@launch;if(loggedOut==null){mutable.value=mutable.value.copy(codexBusy=false);return@launch};applyCodexAuth(CodexAuth(CodexAuthState.DISCONNECTED),generation);val auth=call{api.startCodexAuth(bearer)};if(generation!=codexGeneration)return@launch;mutable.value=mutable.value.copy(codexBusy=false);if(auth!=null)applyCodexAuth(auth,generation)}}
 fun logoutCodex(){runCodexCommand{api.logoutCodex(it)}}
 private fun runCodexCommand(block:suspend(String)->CodexAuth){val bearer=token?:return;if(mutable.value.codexBusy||codexCommandJob?.isActive==true)return;val generation=nextCodexGeneration(cancelPoll=true);mutable.value=mutable.value.copy(codexBusy=true,error=null);codexCommandJob=viewModelScope.launch{val auth=call{block(bearer)};if(generation!=codexGeneration)return@launch;mutable.value=mutable.value.copy(codexBusy=false);if(auth!=null)applyCodexAuth(auth,generation)}}
 private fun nextCodexGeneration(cancelPoll:Boolean):Long{codexGeneration++;codexStatusJob?.cancel();if(cancelPoll)codexPoll?.cancel();return codexGeneration}
 private fun applyCodexAuth(auth:CodexAuth,generation:Long=codexGeneration){if(generation!=codexGeneration)return;mutable.value=mutable.value.copy(codexAuth=auth);when(auth.state){CodexAuthState.CONNECTED->loadCodexModels(generation);CodexAuthState.PENDING->if(screenActive)startCodexPoll(generation);CodexAuthState.DISCONNECTED->{codexPoll?.cancel();tokens.resetCodexProviders();mutable.value=mutable.value.copy(codexAuth=CodexAuth(CodexAuthState.DISCONNECTED),codexModels=emptyList(),provider=HarnessProvider.AGENT,selectedModel=null)};CodexAuthState.UNKNOWN->Unit}}
 private fun loadCodexModels(generation:Long){val bearer=token?:return;viewModelScope.launch{val models=call{api.codexModels(bearer)}?:return@launch;if(generation!=codexGeneration)return@launch;mutable.value=mutable.value.copy(codexModels=models);normalizeCodexSelection()}}
 private fun normalizeCodexSelection(){val c=mutable.value.selected?:return;if(c.kind==ConversationKind.EE)return;val models=mutable.value.codexModels;val selected=mutable.value.selectedModel?.takeIf{it in models}?:tokens.model(c.id)?.takeIf{it in models}?:models.firstOrNull();if(selected!=mutable.value.selectedModel)mutable.value=mutable.value.copy(selectedModel=selected);if(models.isNotEmpty())tokens.saveModel(c.id,selected);val unavailable=mutable.value.codexAuth.state==CodexAuthState.DISCONNECTED||mutable.value.codexAuth.state==CodexAuthState.CONNECTED&&selected==null;if(mutable.value.provider==HarnessProvider.CODEX&&unavailable){tokens.saveProvider(c.id,HarnessProvider.AGENT);mutable.value=mutable.value.copy(provider=HarnessProvider.AGENT)}}
 private fun startCodexPoll(generation:Long=codexGeneration){
  if(codexPoll?.isActive==true)return
  val bearer=token?:return
  if(!screenActive||mutable.value.codexAuth.state!=CodexAuthState.PENDING)return
  codexPoll=viewModelScope.launch{
   repeat(CODEX_POLL_LIMIT){
    delay(CODEX_POLL_MS)
    if(!screenActive||generation!=codexGeneration||mutable.value.codexAuth.state!=CodexAuthState.PENDING)return@launch
    val auth=call{api.codexAuthStatus(bearer)}?:return@launch
    if(generation!=codexGeneration)return@launch
    applyCodexAuth(auth,generation)
    if(auth.state!=CodexAuthState.PENDING)return@launch
   }
   if(mutable.value.codexAuth.state==CodexAuthState.PENDING)mutable.value=mutable.value.copy(error="Время ожидания входа Codex истекло. Можно запросить новый код.")
  }
 }
 private fun replace(c:HarnessConversation){mutable.value=mutable.value.copy(selected=c,conversations=mutable.value.conversations.map{if(it.id==c.id)c else it})}
 private fun mutate(block:suspend(String)->Unit){val bearer=token?:return;mutable.value=mutable.value.copy(loading=true,error=null);viewModelScope.launch{call{block(bearer)};mutable.value=mutable.value.copy(loading=false)}}
 private suspend fun<T> call(block:suspend()->T):T?=try{withContext(io){block()}}catch(c:CancellationException){throw c}catch(_:HarnessUnauthorized){tokens.clear();token=null;mutable.value=HarnessState(error="Сессия истекла. Подключите устройство снова.");null}catch(e:Throwable){mutable.value=mutable.value.copy(loading=false,loadingOlder=false,sending=false,error=e.message?:"Ошибка сети");null}
 fun unpair(){pairingJob?.cancel();nextCodexGeneration(cancelPoll=true);codexCommandJob?.cancel();val bearer=token?:return;tokens.moveToPendingRevoke(bearer);pending=bearer;token=null;retryPendingRevoke()}
 fun retryPendingRevoke(){val bearer=pending?:tokens.pendingRevoke()?.also{pending=it}?:run{mutable.value=HarnessState();return};mutable.value=HarnessState(phase=HarnessPhase.Revoking,loading=true);viewModelScope.launch{try{withContext(io){api.revoke(bearer)};tokens.clearPendingRevoke();pending=null;mutable.value=HarnessState()}catch(_:HarnessUnauthorized){tokens.clearPendingRevoke();pending=null;mutable.value=HarnessState()}catch(e:Throwable){mutable.value=HarnessState(phase=HarnessPhase.Revoking,error=e.message)}}}
 companion object{const val MAX_MESSAGE_BYTES=20_000;const val CODEX_POLL_MS=3000L;const val CODEX_POLL_LIMIT=200;fun truncateUtf8(value:String,max:Int):String{var used=0;var end=0;while(end<value.length){val cp=value.codePointAt(end);val chars=Character.charCount(cp);val bytes=String(Character.toChars(cp)).toByteArray(Charsets.UTF_8).size;if(used+bytes>max)break;used+=bytes;end+=chars};return value.substring(0,end)};fun factory(api:HarnessApi,tokens:HarnessTokenStore)=object:ViewModelProvider.Factory{@Suppress("UNCHECKED_CAST")override fun<T:ViewModel>create(modelClass:Class<T>):T=HarnessViewModel(api,tokens) as T}}
}
