package ru.rockxi.fff.ui.harness

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.withContext
import kotlinx.coroutines.test.*
import org.junit.*
import org.junit.Assert.*
import ru.rockxi.fff.data.harness.*
import java.io.ByteArrayInputStream

@OptIn(ExperimentalCoroutinesApi::class) class HarnessViewModelTest{
 private val dispatcher=StandardTestDispatcher();@Before fun before(){Dispatchers.setMain(dispatcher)};@After fun after(){Dispatchers.resetMain()}
 @Test fun `json parses conversation message page and pending send`(){val list=HarnessJson.conversations("""{"items":[{"id":"x","kind":"ee","title":"EE","pinned":true,"archived":false,"createdAt":"a","updatedAt":"b","lastMessage":"hi"}]}""");assertEquals(ConversationKind.EE,list.single().kind);val page=HarnessJson.messages("""{"items":[{"id":"m","sequence":2,"conversationId":"x","role":"user","content":"hi","source":"telegram_user","authorName":"R","createdAt":"z"}],"nextBefore":1}""");assertEquals(1L,page.nextBefore);assertEquals("R",page.items.single().authorName);assertTrue(HarnessJson.send("""{"message":{"id":"m","sequence":2,"conversationId":"x","role":"user","content":"hi","source":"harness","authorName":null,"createdAt":"z"},"answer":null,"pending":true}""").pending)}
 @Test fun `json parses codex status and distinct models`(){assertEquals(CodexAuthState.PENDING,HarnessJson.codexAuth("""{"state":"pending","verificationUrl":"https://auth.openai.com/codex/device","userCode":"ABCD-EFGH"}""").state);assertEquals(listOf("gpt-a","gpt-b"),HarnessJson.models("""{"items":["gpt-a","gpt-a","gpt-b"],"source":"server_allowlist"}"""))}
 @Test fun `device auth UI accepts only pinned official origin`(){assertTrue(isOfficialCodexVerificationUrl("https://auth.openai.com/codex/device"));listOf("http://auth.openai.com/codex/device","https://evil.example/codex/device","https://auth.openai.com.evil.example/codex/device","https://auth.openai.com@evil.example/codex/device","https://evil.example@auth.openai.com/codex/device","https://auth.openai.com:444/codex/device").forEach{assertFalse(it,isOfficialCodexVerificationUrl(it))}}
 @Test fun `send request binds provider and model without leaking model to agent`(){assertEquals("""{"message":"hi","clientMessageId":"id","provider":"codex","model":"gpt-a"}""",HarnessJson.sendRequest("hi","id",HarnessProvider.CODEX,"gpt-a"));assertEquals("""{"message":"hi","clientMessageId":"id","provider":"agent"}""",HarnessJson.sendRequest("hi","id",HarnessProvider.AGENT,null))}
 @Test fun `loads EE first and restores server history`()=runTest(dispatcher){val api=FakeApi();val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();assertEquals(ConversationKind.EE,model.state.value.conversations.first().kind);model.open(api.ee);runCurrent();assertEquals("old",model.state.value.messages.single().content);model.close()}
 @Test fun `draft is durable per conversation`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi();val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);advanceUntilIdle();model.updateDraft("remember me");model.close();model.open(api.regular);assertEquals("remember me",model.state.value.draft)}
 @Test fun `EE retry reuses stable client message id`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{fail=true};val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("send");model.send();runCurrent();val id=api.ids.single();api.fail=false;model.retry();runCurrent();assertEquals(id,api.ids.last());assertEquals(2,api.ids.size);model.close()}
 @Test fun `EE immediate refresh clears pending after fresh assistant reply`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old")),null);api.pages+=MessagePage(listOf(userMessage(api.ee.id,2,"sent"),serverMessage(api.ee.id,3,"fast reply")),null);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("sent");model.send();runCurrent();assertFalse(model.state.value.sending);assertEquals(listOf("sent","fast reply"),model.state.value.messages.map{it.content})}
 @Test fun `EE immediate refresh does not clear pending for historical assistant`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old")),null);api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old"),userMessage(api.ee.id,2,"sent")),null);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("sent");model.send();runCurrent();assertTrue(model.state.value.sending);model.close()}
 @Test fun `bounded reader rejects overflow`(){try{readBounded(ByteArrayInputStream(ByteArray(11)),-1,10);fail()}catch(_:IllegalStateException){}}
 @Test fun `utf8 truncation respects bytes and never splits emoji`(){assertEquals("a😀",HarnessViewModel.truncateUtf8("a😀b",5));assertEquals("",HarnessViewModel.truncateUtf8("😀",3))}
 @Test fun `edited failed text receives a new client id`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{fail=true};val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);runCurrent();model.updateDraft("first");model.send();runCurrent();val first=api.ids.single();model.updateDraft("edited");model.send();runCurrent();assertNotEquals(first,api.ids.last())}
 @Test fun `codex model selection persists and is sent only for ordinary conversation`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.CONNECTED)};val model=HarnessViewModel(api,store,dispatcher);model.setScreenActive(true);advanceUntilIdle();model.open(api.regular);advanceUntilIdle();model.selectProvider(HarnessProvider.CODEX);model.selectModel("gpt-b");model.updateDraft("codex");model.send();advanceUntilIdle();assertEquals(HarnessProvider.CODEX,api.providers.last());assertEquals("gpt-b",api.models.last());assertEquals("gpt-b",store.model(api.regular.id));model.open(api.ee);runCurrent();model.updateDraft("telegram");model.send();runCurrent();model.setScreenActive(false);advanceUntilIdle();assertEquals(HarnessProvider.AGENT,api.providers.last());assertNull(api.models.last())}
 @Test fun `stale stored model falls back to server first model`()=runTest(dispatcher){val store=MemoryTokens("token").apply{saveProvider("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",HarnessProvider.CODEX);saveModel("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","gone")};val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.CONNECTED)};val model=HarnessViewModel(api,store,dispatcher);model.setScreenActive(true);advanceUntilIdle();model.open(api.regular);advanceUntilIdle();assertEquals("gpt-a",model.state.value.selectedModel);assertEquals(HarnessProvider.CODEX,model.state.value.provider)}
 @Test fun `stored codex preference survives before first auth status arrives`()=runTest(dispatcher){val store=MemoryTokens("token").apply{saveProvider("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",HarnessProvider.CODEX);saveModel("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","gpt-a")};val api=FakeApi();val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);runCurrent();assertEquals(CodexAuthState.UNKNOWN,model.state.value.codexAuth.state);assertEquals(HarnessProvider.CODEX,model.state.value.provider);assertEquals(HarnessProvider.CODEX,store.provider(api.regular.id))}
 @Test fun `retry keeps original codex provider model and id after UI changes`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.CONNECTED);fail=true};val model=HarnessViewModel(api,store,dispatcher);model.setScreenActive(true);advanceUntilIdle();model.open(api.regular);advanceUntilIdle();model.selectProvider(HarnessProvider.CODEX);model.selectModel("gpt-b");model.updateDraft("retry");model.send();runCurrent();val id=api.ids.single();model.selectProvider(HarnessProvider.AGENT);api.fail=false;model.retry();advanceUntilIdle();assertEquals(listOf(id,id),api.ids);assertEquals(listOf(HarnessProvider.CODEX,HarnessProvider.CODEX),api.providers.takeLast(2));assertEquals(listOf("gpt-b","gpt-b"),api.models.takeLast(2))}
 @Test fun `pending codex polling stops while screen is hidden`()=runTest(dispatcher){val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","CODE")};val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);model.setScreenActive(true);runCurrent();advanceTimeBy(HarnessViewModel.CODEX_POLL_MS);runCurrent();val before=api.statusCalls;model.setScreenActive(false);advanceTimeBy(HarnessViewModel.CODEX_POLL_MS*3);runCurrent();assertEquals(before,api.statusCalls)}
 @Test fun `delayed disconnected refresh cannot overwrite newer pending login`()=runTest(dispatcher){val old=CompletableDeferred<CodexAuth>();val api=FakeApi().apply{statusGate=old;startResult=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","NEW")};val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);model.setScreenActive(true);runCurrent();model.startCodexAuth();runCurrent();assertEquals(CodexAuthState.PENDING,model.state.value.codexAuth.state);model.setScreenActive(false);old.complete(CodexAuth(CodexAuthState.DISCONNECTED));advanceUntilIdle();assertEquals(CodexAuthState.PENDING,model.state.value.codexAuth.state)}
 @Test fun `delayed connected refresh cannot overwrite logout`()=runTest(dispatcher){val old=CompletableDeferred<CodexAuth>();val api=FakeApi().apply{statusGate=old;logoutResult=CodexAuth(CodexAuthState.DISCONNECTED)};val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);model.setScreenActive(true);runCurrent();model.logoutCodex();runCurrent();assertEquals(CodexAuthState.DISCONNECTED,model.state.value.codexAuth.state);old.complete(CodexAuth(CodexAuthState.CONNECTED));advanceUntilIdle();assertEquals(CodexAuthState.DISCONNECTED,model.state.value.codexAuth.state);assertTrue(model.state.value.codexModels.isEmpty())}
 @Test fun `new code serially logs out before starting device flow`()=runTest(dispatcher){val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","OLD");startResult=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","NEW")};val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);model.restartCodexAuth();advanceUntilIdle();assertEquals(listOf("logout","start"),api.authActions);assertEquals("NEW",model.state.value.codexAuth.userCode)}
 @Test fun `poll exhaustion remains recoverable with restart action`()=runTest(dispatcher){val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","OLD");startResult=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","NEW")};val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);model.setScreenActive(true);advanceTimeBy(HarnessViewModel.CODEX_POLL_MS*HarnessViewModel.CODEX_POLL_LIMIT+1);runCurrent();assertEquals(CodexAuthState.PENDING,model.state.value.codexAuth.state);assertTrue(model.state.value.error!!.contains("истекло"));model.setScreenActive(false);model.restartCodexAuth();advanceUntilIdle();assertEquals(listOf("logout","start"),api.authActions);assertEquals("NEW",model.state.value.codexAuth.userCode);assertNull(model.state.value.error)}
 @Test fun `restart logout success and device failure stays truthfully disconnected`()=runTest(dispatcher){val store=MemoryTokens("token").apply{saveProvider("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",HarnessProvider.CODEX);saveModel("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","gpt-a")};val api=FakeApi().apply{auth=CodexAuth(CodexAuthState.PENDING,"https://auth.openai.com/codex/device","OLD");failStart=true};val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);runCurrent();model.restartCodexAuth();advanceUntilIdle();assertEquals(listOf("logout","start"),api.authActions);assertEquals(CodexAuthState.DISCONNECTED,model.state.value.codexAuth.state);assertNull(model.state.value.codexAuth.userCode);assertTrue(model.state.value.codexModels.isEmpty());assertEquals(HarnessProvider.AGENT,model.state.value.provider);assertEquals(HarnessProvider.AGENT,store.provider(api.regular.id));assertEquals("device failed",model.state.value.error)}
 @Test fun `EE polling merges latest without dropping loaded messages or cursor`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"older"),serverMessage(api.ee.id,10,"latest")),1);api.pages+=MessagePage(listOf(serverMessage(api.ee.id,11,"new")),10);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.setScreenActive(true);advanceTimeBy(3001);runCurrent();assertEquals(listOf("older","latest","new"),model.state.value.messages.map{it.content});assertEquals(1L,model.state.value.nextBefore);model.setScreenActive(false)}
 @Test fun `activity and message labels are robust`(){assertEquals("08.09.2026 · 12:34",formatHarnessActivity("2026-09-08T12:34:00+03:00"));assertEquals("bad-date",formatHarnessActivity("bad-date"));val m=ServerMessage("m",1,"c","tool","ok","telegram-user","Rock", "z");assertEquals("TOOL · TELEGRAM · Rock",messageLabel(m))}
 @Test fun `tail following only remains near actual bottom`(){assertTrue(shouldFollowHarnessTail(null,0));assertTrue(shouldFollowHarnessTail(9,10));assertTrue(shouldFollowHarnessTail(7,10));assertFalse(shouldFollowHarnessTail(6,10));assertFalse(shouldFollowHarnessTail(null,10))}
 @Test fun `scroll events disable follow before incoming tail and only restore near bottom`(){var follow=true;follow=nextHarnessFollowTail(follow,false,true,9,10);assertFalse(follow);/* incoming last id keeps this state */assertFalse(nextHarnessFollowTail(follow,true,true,9,11));follow=nextHarnessFollowTail(follow,true,false,4,11);assertFalse(follow);follow=nextHarnessFollowTail(follow,false,true,4,11);assertFalse(follow);follow=nextHarnessFollowTail(follow,true,false,10,11);assertTrue(follow)}
 @Test fun `tail animation synchronously refuses active scrolling even with stale follow state`(){assertFalse(shouldAutoScrollHarnessTail(true,true));assertFalse(shouldAutoScrollHarnessTail(false,false));assertTrue(shouldAutoScrollHarnessTail(true,false))}
}
private fun serverMessage(id:String,sequence:Long,text:String)=ServerMessage("m$sequence",sequence,id,"assistant",text,"agent",null,"z")
private fun userMessage(id:String,sequence:Long,text:String)=ServerMessage("m$sequence",sequence,id,"user",text,"telegram_user",null,"z")
private class MemoryTokens(var value:String?=null,var pending:String?=null):HarnessTokenStore{val data=mutableMapOf<String,String>();val pendingData=mutableMapOf<String,PendingHarnessMessage>();override fun deviceId()="d";override fun load()=value;override fun save(token:String){value=token};override fun clear(){value=null};override fun pendingRevoke()=pending;override fun moveToPendingRevoke(token:String){pending=token;value=null};override fun clearPendingRevoke(){pending=null};override fun draft(id:String)=data["d$id"]?:"";override fun saveDraft(id:String,value:String){data["d$id"]=value};override fun pendingMessage(id:String)=pendingData[id];override fun savePendingMessage(id:String,value:PendingHarnessMessage?){if(value==null)pendingData.remove(id)else pendingData[id]=value};override fun provider(id:String)=data["p$id"]?.let(HarnessProvider::valueOf)?:HarnessProvider.AGENT;override fun saveProvider(id:String,value:HarnessProvider){data["p$id"]=value.name};override fun resetCodexProviders(){data.keys.filter{it.startsWith("p")}.toList().forEach(data::remove)};override fun model(id:String)=data["m$id"];override fun saveModel(id:String,value:String?){if(value==null)data.remove("m$id")else data["m$id"]=value}}
private class FakeApi:HarnessApi{val pages=ArrayDeque<MessagePage>();val ee=HarnessConversation("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",ConversationKind.EE,"EE",true,false,"a","z",null);val regular=HarnessConversation("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",ConversationKind.HARNESS,"Chat",false,false,"a","b",null);val ids=mutableListOf<String>();val providers=mutableListOf<HarnessProvider>();val models=mutableListOf<String?>();val authActions=mutableListOf<String>();var fail=false;var auth=CodexAuth(CodexAuthState.DISCONNECTED);var startResult:CodexAuth?=null;var logoutResult=CodexAuth(CodexAuthState.DISCONNECTED);var failStart=false;var failLogout=false;var statusGate:CompletableDeferred<CodexAuth>?=null;var statusCalls=0
 override suspend fun start(deviceId:String)=PairStart("p","C","s");override suspend fun poll(pairingId:String,pollSecret:String)=PollResult.Token("token");override suspend fun revoke(token:String){};override suspend fun listConversations(token:String,archived:Boolean)=listOf(regular,ee);override suspend fun createConversation(token:String,title:String)=regular.copy(title=title);override suspend fun updateConversation(token:String,id:String,title:String?,archived:Boolean?)=regular.copy(title=title?:regular.title,archived=archived?:false);override suspend fun deleteConversation(token:String,id:String){};override suspend fun messages(token:String,id:String,before:Long?)=if(pages.isNotEmpty())pages.removeFirst() else MessagePage(listOf(ServerMessage("m",1,id,"assistant","old","agent",null,"z")),null);override suspend fun send(token:String,id:String,message:String,clientMessageId:String,provider:HarnessProvider,model:String?):SendResult{ids+=clientMessageId;providers+=provider;models+=model;if(fail)error("offline");val m=ServerMessage("u",2,id,"user",message,"harness",null,"z");return SendResult(m,null,id==ee.id)};override suspend fun codexAuthStatus(token:String):CodexAuth{statusCalls++;return statusGate?.let{withContext(NonCancellable){it.await()}}?:auth};override suspend fun startCodexAuth(token:String):CodexAuth{authActions+="start";if(failStart)error("device failed");return startResult?:auth};override suspend fun logoutCodex(token:String):CodexAuth{authActions+="logout";if(failLogout)error("logout failed");return logoutResult};override suspend fun codexModels(token:String)=listOf("gpt-a","gpt-b") }
