package ru.rockxi.fff.ui.harness

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.*
import org.junit.*
import org.junit.Assert.*
import ru.rockxi.fff.data.harness.*
import java.io.ByteArrayInputStream

@OptIn(ExperimentalCoroutinesApi::class) class HarnessViewModelTest{
 private val dispatcher=StandardTestDispatcher();@Before fun before(){Dispatchers.setMain(dispatcher)};@After fun after(){Dispatchers.resetMain()}
 @Test fun `json parses conversation message page and pending send`(){val list=HarnessJson.conversations("""{"items":[{"id":"x","kind":"ee","title":"EE","pinned":true,"archived":false,"createdAt":"a","updatedAt":"b","lastMessage":"hi"}]}""");assertEquals(ConversationKind.EE,list.single().kind);val page=HarnessJson.messages("""{"items":[{"id":"m","sequence":2,"conversationId":"x","role":"user","content":"hi","source":"telegram_user","authorName":"R","createdAt":"z"}],"nextBefore":1}""");assertEquals(1L,page.nextBefore);assertEquals("R",page.items.single().authorName);assertTrue(HarnessJson.send("""{"message":{"id":"m","sequence":2,"conversationId":"x","role":"user","content":"hi","source":"harness","authorName":null,"createdAt":"z"},"answer":null,"pending":true}""").pending)}
 @Test fun `loads EE first and restores server history`()=runTest(dispatcher){val api=FakeApi();val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();assertEquals(ConversationKind.EE,model.state.value.conversations.first().kind);model.open(api.ee);runCurrent();assertEquals("old",model.state.value.messages.single().content);model.close()}
 @Test fun `draft is durable per conversation`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi();val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);advanceUntilIdle();model.updateDraft("remember me");model.close();model.open(api.regular);assertEquals("remember me",model.state.value.draft)}
 @Test fun `EE retry reuses stable client message id`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{fail=true};val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("send");model.send();runCurrent();val id=api.ids.single();api.fail=false;model.retry();runCurrent();assertEquals(id,api.ids.last());assertEquals(2,api.ids.size);model.close()}
 @Test fun `EE immediate refresh clears pending after fresh assistant reply`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old")),null);api.pages+=MessagePage(listOf(userMessage(api.ee.id,2,"sent"),serverMessage(api.ee.id,3,"fast reply")),null);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("sent");model.send();runCurrent();assertFalse(model.state.value.sending);assertEquals(listOf("sent","fast reply"),model.state.value.messages.map{it.content})}
 @Test fun `EE immediate refresh does not clear pending for historical assistant`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old")),null);api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"old"),userMessage(api.ee.id,2,"sent")),null);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.updateDraft("sent");model.send();runCurrent();assertTrue(model.state.value.sending);model.close()}
 @Test fun `bounded reader rejects overflow`(){try{readBounded(ByteArrayInputStream(ByteArray(11)),-1,10);fail()}catch(_:IllegalStateException){}}
 @Test fun `utf8 truncation respects bytes and never splits emoji`(){assertEquals("a😀",HarnessViewModel.truncateUtf8("a😀b",5));assertEquals("",HarnessViewModel.truncateUtf8("😀",3))}
 @Test fun `edited failed text receives a new client id`()=runTest(dispatcher){val store=MemoryTokens("token");val api=FakeApi().apply{fail=true};val model=HarnessViewModel(api,store,dispatcher);advanceUntilIdle();model.open(api.regular);runCurrent();model.updateDraft("first");model.send();runCurrent();val first=api.ids.single();model.updateDraft("edited");model.send();runCurrent();assertNotEquals(first,api.ids.last())}
 @Test fun `EE polling merges latest without dropping loaded messages or cursor`()=runTest(dispatcher){val api=FakeApi();api.pages+=MessagePage(listOf(serverMessage(api.ee.id,1,"older"),serverMessage(api.ee.id,10,"latest")),1);api.pages+=MessagePage(listOf(serverMessage(api.ee.id,11,"new")),10);val model=HarnessViewModel(api,MemoryTokens("token"),dispatcher);advanceUntilIdle();model.open(api.ee);runCurrent();model.setScreenActive(true);advanceTimeBy(3001);runCurrent();assertEquals(listOf("older","latest","new"),model.state.value.messages.map{it.content});assertEquals(1L,model.state.value.nextBefore);model.setScreenActive(false)}
 @Test fun `activity and message labels are robust`(){assertEquals("08.09.2026 · 12:34",formatHarnessActivity("2026-09-08T12:34:00+03:00"));assertEquals("bad-date",formatHarnessActivity("bad-date"));val m=ServerMessage("m",1,"c","tool","ok","telegram-user","Rock", "z");assertEquals("TOOL · TELEGRAM · Rock",messageLabel(m))}
 @Test fun `tail following only remains near actual bottom`(){assertTrue(shouldFollowHarnessTail(null,0));assertTrue(shouldFollowHarnessTail(9,10));assertTrue(shouldFollowHarnessTail(7,10));assertFalse(shouldFollowHarnessTail(6,10));assertFalse(shouldFollowHarnessTail(null,10))}
 @Test fun `scroll events disable follow before incoming tail and only restore near bottom`(){var follow=true;follow=nextHarnessFollowTail(follow,false,true,9,10);assertFalse(follow);/* incoming last id keeps this state */assertFalse(nextHarnessFollowTail(follow,true,true,9,11));follow=nextHarnessFollowTail(follow,true,false,4,11);assertFalse(follow);follow=nextHarnessFollowTail(follow,false,true,4,11);assertFalse(follow);follow=nextHarnessFollowTail(follow,true,false,10,11);assertTrue(follow)}
 @Test fun `tail animation synchronously refuses active scrolling even with stale follow state`(){assertFalse(shouldAutoScrollHarnessTail(true,true));assertFalse(shouldAutoScrollHarnessTail(false,false));assertTrue(shouldAutoScrollHarnessTail(true,false))}
}
private fun serverMessage(id:String,sequence:Long,text:String)=ServerMessage("m$sequence",sequence,id,"assistant",text,"agent",null,"z")
private fun userMessage(id:String,sequence:Long,text:String)=ServerMessage("m$sequence",sequence,id,"user",text,"telegram_user",null,"z")
private class MemoryTokens(var value:String?=null,var pending:String?=null):HarnessTokenStore{val data=mutableMapOf<String,String>();override fun deviceId()="d";override fun load()=value;override fun save(token:String){value=token};override fun clear(){value=null};override fun pendingRevoke()=pending;override fun moveToPendingRevoke(token:String){pending=token;value=null};override fun clearPendingRevoke(){pending=null};override fun draft(id:String)=data["d$id"]?:"";override fun saveDraft(id:String,value:String){data["d$id"]=value};override fun pendingMessage(id:String)=data["pi$id"]?.let{PendingHarnessMessage(it,data["pt$id"]!!)};override fun savePendingMessage(id:String,value:PendingHarnessMessage?){if(value==null){data.remove("pi$id");data.remove("pt$id")}else{data["pi$id"]=value.clientId;data["pt$id"]=value.text}}}
private class FakeApi:HarnessApi{val pages=ArrayDeque<MessagePage>();val ee=HarnessConversation("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",ConversationKind.EE,"EE",true,false,"a","z",null);val regular=HarnessConversation("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",ConversationKind.HARNESS,"Chat",false,false,"a","b",null);val ids=mutableListOf<String>();var fail=false
 override suspend fun start(deviceId:String)=PairStart("p","C","s");override suspend fun poll(pairingId:String,pollSecret:String)=PollResult.Token("token");override suspend fun revoke(token:String){};override suspend fun listConversations(token:String,archived:Boolean)=listOf(regular,ee);override suspend fun createConversation(token:String,title:String)=regular.copy(title=title);override suspend fun updateConversation(token:String,id:String,title:String?,archived:Boolean?)=regular.copy(title=title?:regular.title,archived=archived?:false);override suspend fun deleteConversation(token:String,id:String){};override suspend fun messages(token:String,id:String,before:Long?)=if(pages.isNotEmpty())pages.removeFirst() else MessagePage(listOf(ServerMessage("m",1,id,"assistant","old","agent",null,"z")),null);override suspend fun send(token:String,id:String,message:String,clientMessageId:String):SendResult{ids+=clientMessageId;if(fail)error("offline");val m=ServerMessage("u",2,id,"user",message,"harness",null,"z");return SendResult(m,null,id==ee.id)} }
